/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package timbiriche;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author pc
 */
public class FrameJuego extends javax.swing.JFrame {
    private Tablero tablero;
    
    /**
     * Creates new form frameJuego
     * @param listaDeJugadores
     */
    
    //niaaaa
    public FrameJuego(List<Jugador> listaDeJugadores) {
        initComponents();
        this.setSize(1300, 950);
        tablero = new Tablero(listaDeJugadores);
        tablero.setLocation(25, 25);
        JPanel panel = tablero.getPanel();
        panel.setLocation(900,25);
        this.add(panel);
        //lienzo.setSize(800, 1300);
        this.add(tablero);
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        Graphics2D g2 = (Graphics2D) g.create();
        /*
        System.out.println(lienzo.getTurnoJugador().getNombre());
        Avatar avatar = lienzo.getTurnoJugador().getAvatar();
        avatar.setTamaño(70);
        avatar.setEjeX(1037);
        avatar.setEjeY(285);
        avatar.pintar(g2);*/
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
